### PR TITLE
better fuzz harness & integration

### PR DESCRIPTION
**Pull request by evanrichter**
I recommend dropping the commits from the previous PR with `git rebase -i HEAD~2` and changing each "pick" to "drop", then there won't be any merge conflicts

### CODE REVIEW

**Comment by xansec** [comment]
I rebased but a lot of the source files are showing as modified. Is this expected? Is your master up to date with upstream?

**Comment by evanrichter** [comment]
yeah, it says I'm 2 commits ahead of upstream: https://github.com/evanrichter/orz

**Comment by evanrichter** [comment]
you know, I think it's my ssh signature, and I must have rebased one of the recent commits and that adds my signature.

I'll fix it up in a sec

**Comment by evanrichter** [comment]
nope, it's code formatting :sob:

**Comment by evanrichter** [comment]
it was actually somehow both and I'm just glad that is cleaned up now :sweat_smile: 

should be ready to merge

**Comment by xansec** [comment]
Looks a lot better now!

**Pull request merged**
